# Generated by Django 2.2.13 on 2021-01-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_credentialapplication_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='has_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='researcher_category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Student'), (7, 'Graduate Student'), (1, 'Postdoc'), (2, 'Academic Researcher'), (3, 'Hospital Researcher'), (4, 'Industry Researcher'), (5, 'Government Researcher'), (6, 'Independent Researcher')], null=True),
        ),
    ]
